In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print(empty_array);

print("\n")

ones_array = np.ones((4, 2))
print(ones_array)

print("\n")

# Specify the shape, fill value, and data type
shape = (2, 2)
fill_value = 2
filled_array = np.full(shape, fill_value, dtype=int)
print(filled_array)

print("\n")

# Create a new array of zeros with the same shape and type as the reference array
zeros_like_array = np.zeros_like(filled_array)
print(zeros_like_array)

print("\n")

# Create a new array of ones with the same shape and type as the reference array
ones_like_array = np.ones_like(filled_array)
print(ones_like_array)

print("\n")

new_list = [1, 2, 3, 4]
# Convert the list to a NumPy array
numpy_array = np.array(new_list)
print(numpy_array)


[[5.e-324 5.e-324]
 [5.e-324 5.e-324]]


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[2 2]
 [2 2]]


[[0 0]
 [0 0]]


[[1 1]
 [1 1]]


[1 2 3 4]


In [ ]:
import numpy as np

# Create an array with values from 10 to 49
array = np.arange(10, 50)
print("Array with values ranging from 10 to 49:",array)

print("\n")

# Create an array with values from 0 to 8
array = np.arange(9)
# Reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)
print("3x3 Matrix with values from 0 to 8:")
print(matrix)

print("\n")

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

print("\n")

# Create a random array of size 30 with values between 0 and 1
random_array = np.random.random(30)
# Calculate the mean of the array
mean_value = random_array.mean()
print("Random Array of Size 30:")
print(random_array)
print("\nMean of the Array:", mean_value)

print("\n")

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))
# Find the minimum and maximum values in the array
min_value = random_array.min()
max_value = random_array.max()
print("10x10 Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

print("\n")

# Create a zero array of size 10
zero_array = np.zeros(10)
# Replace the 5th element (index 4) with 1
zero_array[4] = 1
print("Array after replacing the 5th element with 1:")
print(zero_array)

print("\n")

arr = np.array([1, 2, 0, 0, 4, 0])
# Reverse the array using np.flip()
reversed_arr = np.flip(arr)
print("Reversed Array:")
print(reversed_arr)

print("\n")

# Specify the size of the 2D array
size = 3
# Create an array of ones
array = np.ones((size, size))
# Set the inner elements (excluding the border) to zero
array[1:-1, 1:-1] = 0
print("2D Array with 1 on border and 0 inside:")
print(array)

print("\n")

# Create an 8x8 array with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
# Fill the checkerboard pattern (1 for black squares, 0 for white squares)
checkerboard[::2, ::2] = 1  # Fill the even rows and columns with 1
checkerboard[1::2, 1::2] = 1  # Fill the odd rows and columns with 1
print("8x8 Checkerboard Pattern:")
print(checkerboard)

Array with values ranging from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Random Array of Size 30:
[0.30430615 0.62586595 0.42117615 0.62978954 0.05291441 0.23429619
 0.14363946 0.02114464 0.27062931 0.61864851 0.18344578 0.69132676
 0.13754967 0.89145742 0.84516176 0.33476846 0.63337648 0.46018731
 0.90683613 0.49114357 0.57737993 0.08785961 0.61774492 0.10101692
 0.60072095 0.54389862 0.1534463  0.06134813 0.09564985 0.04559872]

Mean of the Array: 0.39274425333126395


10x10 Random Array:
[[0.28530344 0.19822983 0.66934817 0.10623503 0.4541487  0.79096254
  0.42663529 0.80615715 0.8128511  0.37589354]
 [0.99450441 0.19887564 0.27981358 0.05245106 0.05076153 0.89822482
  0.94877461 0.15018234 0.15952402 0.31617105]
 [0.89477436 0.17113613 0.64317223 0.71771605 0.8239178

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

array_sum = x + y
vector_sum = v + w
print("Sum of x and y:")
print(array_sum)
print("\nSum of v and w:")
print(vector_sum)

print("\n")

array_difference = x - y
vector_difference = v - w
print("Difference of x and y:")
print(array_difference)
print("\nDifference of v and w:")
print(vector_difference)

print("\n")

x_multiply = x * 3
v_multiply = v * 2
print("Array x multiplied by 3:")
print(x_multiply)
print("\nVector v multiplied by 2:")
print(v_multiply)

print("\n")

# Square each element
x_squared = x ** 2
v_squared = np.square(v)
print("Squared elements of x:")
print(x_squared)
print("\nSquared elements of v:")
print(v_squared)

print("\n")

# Calculate the dot product
dot_product1 = np.dot(v, w)
dot_product2 = np.dot(x, v)
dot_product3 = np.dot(x, y)
print("Dot Product of v and w:")
print(dot_product1)
print("Dot Product of x and v:")
print(dot_product2)
print("Dot Product of x and y:")
print(dot_product3)

print("\n")

# Concatenate x and y along rows (axis 0)
concat_xy = np.concatenate((x, y), axis=0)
# Concatenate v and w along columns (axis 0, making them 2D first)
v_reshaped = v.reshape(-1, 1)  # Reshape v to a column vector
w_reshaped = w.reshape(-1, 1)  # Reshape w to a column vector
concat_vw = np.concatenate((v_reshaped, w_reshaped), axis=1)
print("Concatenated x and y along rows:")
print(concat_xy)
print("\nConcatenated v and w along columns:")
print(concat_vw)

Sum of x and y:
[[ 6  8]
 [10 13]]

Sum of v and w:
[20 22]


Difference of x and y:
[[-4 -4]
 [-4 -3]]

Difference of v and w:
[-2 -2]


Array x multiplied by 3:
[[ 3  6]
 [ 9 15]]

Vector v multiplied by 2:
[18 20]


Squared elements of x:
[[ 1  4]
 [ 9 25]]

Squared elements of v:
[ 81 100]


Dot Product of v and w:
219
Dot Product of x and v:
[29 77]
Dot Product of x and y:
[[19 22]
 [50 58]]


Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


In [ ]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.eye(2)  # Identity matrix of size 2x2

# Multiply A by A^-1
A_A_inv = np.dot(A, A_inv)

print("A * A^-1 (should be identity matrix):")
print(A_A_inv)

# Check if it is close to identity
print("\nCheck if A * A^-1 is identity matrix:", np.allclose(A_A_inv, identity_matrix))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:")
print(AB)

print("\nBA:")
print(BA)

# Check if AB is equal to BA
print("\nCheck if AB == BA:", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

print("\n(AB)^T:")
print(AB_T)

print("\nB^T * A^T:")
print(B_T_A_T)

# Check if (AB)^T is equal to B^T * A^T
print("\nCheck if (AB)^T == B^T * A^T:", np.array_equal(AB_T, B_T_A_T))


A * A^-1 (should be identity matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Check if A * A^-1 is identity matrix: True

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

Check if AB == BA: False

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Check if (AB)^T == B^T * A^T: True


In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant matrix B
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse method
X = np.dot(A_inv, B)

print("The solution is:")
print(f"x = {X[0]}, y = {X[1]}, z = {X[2]}")


The solution is:
x = 2.0, y = 1.0, z = -2.0


In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant matrix B
B = np.array([-1, -3, 9])

# Using np.linalg.inv to find the inverse of A
A_inv = np.linalg.inv(A)

# Solving for X using the formula X = A^-1 * B
X = np.dot(A_inv, B)

# Output the solution
print("The solution is:")
print(f"x = {X[0]}, y = {X[1]}, z = {X[2]}")


The solution is:
x = 2.0, y = 1.0, z = -2.0


In [ ]:
import time
import numpy as np

# Generate two lists of size 1,000,000 with random numbers
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

# Measure time taken for element-wise addition using Python lists
start_time = time.time()

result_list = [list1[i] + list2[i] for i in range(len(list1))]

end_time = time.time()
print(f"Time taken for Python list addition: {end_time - start_time:.6f} seconds")

# Convert the lists to NumPy arrays for comparison
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time taken for element-wise addition using NumPy arrays
start_time = time.time()

result_array = array1 + array2  # Element-wise addition

end_time = time.time()
print(f"Time taken for NumPy array addition: {end_time - start_time:.6f} seconds")


Time taken for Python list addition: 0.157066 seconds
Time taken for NumPy array addition: 0.004623 seconds


In [ ]:
import time
import numpy as np

# Generate two lists of size 1,000,000 with random numbers
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

# Measure time taken for element-wise multiplication using Python lists
start_time = time.time()

result_list = [list1[i] * list2[i] for i in range(len(list1))]

end_time = time.time()
print(f"Time taken for Python list multiplication: {end_time - start_time:.6f} seconds")

# Convert the lists to NumPy arrays for comparison
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time taken for element-wise multiplication using NumPy arrays
start_time = time.time()

result_array = array1 * array2  # Element-wise multiplication

end_time = time.time()
print(f"Time taken for NumPy array multiplication: {end_time - start_time:.6f} seconds")


Time taken for Python list multiplication: 0.191765 seconds
Time taken for NumPy array multiplication: 0.004895 seconds


In [ ]:
import time
import numpy as np

# Generate two lists of size 1,000,000 with random numbers
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

# Measure time taken for dot product using Python lists
start_time = time.time()

dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))

end_time = time.time()
print(f"Time taken for Python list dot product: {end_time - start_time:.6f} seconds")

# Convert the lists to NumPy arrays for comparison
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time taken for dot product using NumPy arrays
start_time = time.time()

dot_product_array = np.dot(array1, array2)

end_time = time.time()
print(f"Time taken for NumPy array dot product: {end_time - start_time:.6f} seconds")


Time taken for Python list dot product: 0.165823 seconds
Time taken for NumPy array dot product: 0.002061 seconds


In [ ]:
import time
import numpy as np

# Generate two 1000x1000 matrices with random values using Python lists
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

# Function to perform matrix multiplication using Python lists
def matrix_multiplication_lists(A, B):
    result = [[0] * len(B[0]) for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

# Measure time taken for matrix multiplication using Python lists
start_time = time.time()

result_list = matrix_multiplication_lists(matrix1, matrix2)

end_time = time.time()
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time:.6f} seconds")

# Convert the lists to NumPy arrays for comparison
array1 = np.array(matrix1)
array2 = np.array(matrix2)

# Measure time taken for matrix multiplication using NumPy arrays
start_time = time.time()

result_array = np.dot(array1, array2)

end_time = time.time()
print(f"Time taken for matrix multiplication using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken for matrix multiplication using Python lists: 295.981077 seconds
Time taken for matrix multiplication using NumPy arrays: 2.497121 seconds
